# Generated by Django 4.2.7 on 2023-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Artist name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='artists/%Y/%m/%d/', verbose_name='Photo')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
        ),
    ]
