# Generated by Django 4.2.7 on 2023-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_genre_artist_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Genre name'),
        ),
    ]
