# Generated by Django 4.2.7 on 2023-11-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-time_created']},
        ),
    ]
